config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.server:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.server.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-jade-greyhound.sh
        container: qc.acc_stuffy-turquoise-kangaroo
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-firebrick-echidna.sh
        container: qc.doc_sickly-carmine-burmese
      github.com/cessda/cessda.cmv.server git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-platinum-dog.sh
        container: qc.doc_hazy-cerulean-sponge
      github.com/cessda/cessda.cmv.server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-goldenrod-serval.sh
        container: qc.doc_cloudy-cardinal-badger
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-khaki-ibis.sh
        container: qc.lic_hazy-coral-dogfish
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-grey-chinchilla.sh
        container: qc.met_foggy-taupe-turkey
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.server checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ruby-pig.sh
        container: qc.sty_lanky-pink-toucan
      github.com/cessda/cessda.cmv.server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-beige-goat.sh
        container: qc.sty_freaky-salmon-wrasse
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-mauve-dog.sh
        container: qc.ver_shaky-cerise-ladybird
timeout: 5400
